package pokewrap

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// generated by https://mholt.github.io/json-to-go/
type LocationArea struct {
	Count    int    `json:"count"`
	Next     string `json:"next"`
	Previous any    `json:"previous"`
	Results  []struct {
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"results"`
}

func GetMapJSON(mapPage int) (LocationArea, error) {
	// https://pokeapi.co/api/v2/location-area
	// ?limit=20
	// &offset=20 * mapPage

	// https://pokeapi.co/api/v2/location-area?limit=20&offset=0

	url := fmt.Sprintf("https://pokeapi.co/api/v2/location-area?limit=%v&offset=%v", 20, 20*mapPage)
	resp, err := http.Get(url)
	if err != nil {
		return LocationArea{}, err
	}
	defer resp.Body.Close()

	if resp.StatusCode > 299 {
		return LocationArea{}, fmt.Errorf("response failed with status code: %d", resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return LocationArea{}, err
	}

	area := LocationArea{}
	if err = json.Unmarshal(data, &area); err != nil {
		return LocationArea{}, err
	}

	fmt.Println(url)

	// fmt.Print(area)
	// fmt.Print(pretty(string(data)))
	_ = pretty

	return area, nil
}

func pretty(str string) (string, error) {
	var prettyJSON bytes.Buffer
	if err := json.Indent(&prettyJSON, []byte(str), "", "    "); err != nil {
		return "", err
	}

	return prettyJSON.String(), nil
}
